### ISSUE TITLE
key problem

### ISSUE THREAD

**Issue by emckean** [nivesh2/wordnikDictionary#1]
Hi! Please remove your Wordnik API key from this repo, we ask in our terms of use that you not share your key (http://developer.wordnik.com/#!/terms). We have disabled your key for now, please let us know at apiteam@wordnik.com if you need to apply for another key.

**Comment by nivesh2** [comment]
Okay, thanks for notifying. Actually i was gonna disable my account to disable that key. Thanks again for disabling the key.
